### ISSUE TITLE
will it work for third order categorical features interaction

### ISSUE THREAD

**Issue by Sandy4321** [instagibbs/FactorizationMachine#1]
Great code,  thanks !

Plese help to understand
1
will it work for third order categorical features interaction ?
2
will it run on Windows computer ?

3
will it work for sparse data ?

**Comment by instagibbs** [comment]
no idea, haha. Been many years since I've looked at Machine Learning. Good luck ;)

**Comment by Sandy4321** [comment]
#https://github.com/jamborta/tffm2    pip install tffm2

# try also https://github.com/orangelle/kerasfm

they say , their code it works for 3r order interactions ?
